<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\Order.Domain\Order.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Orders\CancelOrder\" />
    <Folder Include="Queries_ReadModel\" />
  </ItemGroup>

</Project>
