<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Messaging\DomainEvents\" />
    <Folder Include="Messaging\EventBuses\ymls\" />
    <Folder Include="Persistence\Extensions\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Contracts\BuildingBlocks.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Contracts\Order.Contracts\Order.Contracts.csproj" />
    <ProjectReference Include="..\Order.Application\Order.Application.csproj" />
    <ProjectReference Include="..\Order.Domain\Order.Domain.csproj" />
  </ItemGroup>

</Project>
